### ISSUE TITLE
Support a non-modifier

### ISSUE THREAD

**Issue by statico** [marquete/kibo#3]
Right now you can bind keys with modifiers easily:

```
k.down('ctrl shift q', ...)
```

It would be awesome if I coud bind keys _without_ modifiers:

   k.down('plain q', ...)

I'm not sure if `plain` is the right term. `unmodified` seems too verbose. :)

**Comment by marquete** [comment]
Interesting! And potentially very useful. (: I'll keep this in mind. Again, thanks for your feedback!

**Comment by marquete** [comment]
Now by default the key is bound without modifiers if none are specified.
