### ISSUE TITLE
"ctrl z" listener is fired when "ctrl shift z" is pressed.

### ISSUE THREAD

**Issue by erikvold** [marquete/kibo#9]
imo a listener should only fire when the exact key(s) requested are pressed, and a listener should not fire when more keys are pressed in combination with the requested key(s).

**Comment by erikvold** [comment]
Looks like `Kibo.prototype.matchingKeys` will need to be modified quite a bit.  @marquete what do you think about this one? I'll contribute the patch if you are for this one.

**Comment by erikvold** [comment]
Might want to wait on this until there are tests though.

**Comment by marquete** [comment]
Agreed - it's probably best to wait until I roll out some tests. Thank you!

**Comment by marquete** [comment]
Fixed in https://github.com/marquete/kibo/commit/98d857538a2eb5eb6ef7d02638ae3c3604f39674.
